### ISSUE TITLE
How does use?

### ISSUE THREAD

**Issue by stoneWeb** [sigmaai/semantic-segmentation#1]
How does use?
where is requirements.txt?

**Comment by NeilNie** [comment]
Hi @stoneWeb, I have to update this repo. I will let you know when I push the commit. Thanks!

**Comment by NeilNie** [comment]
@stoneWeb I updated the README file with some instructions. The best way to run (inferencing) is to use the `test.py` file. Just modify the `path` variable to the image(s) that you want to test, it will automatically save the results. Training doesn't work very well. I need to fix that. Stay in tune for that. Thanks! Let me know if you have any other issues or problems.
