### ISSUE TITLE
What do we mean by "training doesn't work very well"?

### ISSUE THREAD

**Issue by sumantk** [sigmaai/semantic-segmentation#2]
In the readme file, there is a mention - "training doesn't work very well."

What does it mean by that? Request you to please elaborate. 

Also, if there is a way to fix it, please suggest.  

Also, can you suggest what is the size of the training data required for training?

**Comment by NeilNie** [comment]
Hello,

Thanks for the issue. I wasn't being clear in the readme. I meant to say that the training script has some bugs right now. You can't just take the training script and begin to train your own model. 

You should have at least 20K training samples. In general, you want to maximize both the quantity and quality of the training data. 

I hope this helps!

Neil
